[package]
name = "qqself-lambda-entries-health"
version = "0.0.0"
edition = "2021"

[dependencies]
lambda_http = "0.9.0"
tokio = { version = "1.35.1", features = ["macros"] }
qqself-api-entries-services = { path = "../services" }

