[package]
name = "qqself-core-bindings-wasm"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.90"
qqself-core = { path = "../core", features = ["wasm"] }
console_error_panic_hook = "0.1.7"
js-sys = { version = "0.3.66" }
