[package]
name = "qqself-client-web-core"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
qqself-core = { path = "../core" }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
