version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client-web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/client-web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/api-sync"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/www"
    schedule:
      interval: "weekly"
