[workspace]
resolver = "2"

members = [
    "core",
    "core-bindings-c",
    "core-bindings-wasm",
    "client-cli",
    "api-entries/services",
    "api-entries/webservice",
    "api-entries/lambda-health",
]

[profile.release]
overflow-checks = true

