[package]
name = "qqself-api-sync"
version = "0.0.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
async-trait = "0.1.68"
env_logger = "0.10.0"
futures = "0.3.28"
lazy_static = "1.4.0"
log = "0.4.17"
qqself-core = { path = "../core", features = ["serde"] }
serde = { version="1.0.164", features = ["derive"] }
tempdir = "0.3.7"
tokio = { version = "1.29.1", features = ["rt", "macros", "time"] }
thiserror = "1.0.40"
# storage-dynamodb
aws-config = { version = "0.55.3", optional = true }
aws-sdk-dynamodb = { version = "0.28.0", optional = true }

[features]
default = []
storage-dynamodb = ["dep:aws-config", "dep:aws-sdk-dynamodb"]
