name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  
  merge_group:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # vergen fails in case of a default shallow clone
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-linux-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-linux
    - name: cache-yarn
      uses: actions/cache@v3
      with:
        path: "client-web/node_modules"
        key: yarn-${{ hashFiles('client-web/yarn.lock') }}
        restore-keys: yarn-
    - run: ./run.sh deps
    - run: ./run.sh build
    - run: ./run.sh test
    - run: ./run.sh lint
  
  build-ios:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.1.app/Contents/Developer
    defaults:
      run:
        working-directory: client-ios
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-macos-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-macos
    - run: make deps
    - run: make bindings
    - run: make build
    - run: echo "make test is disabled. Waiting for XCode 15 fix and new agent"
    - run: make lint-check

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: ./run.sh deps
    - run: ./run.sh deploy www
    - run: ./run.sh deploy client-web
